name = "JuliaPredict"
uuid = "f6485ecc-8eed-4ebe-b651-64a0290b6f16"
authors = ["chaussr"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
